### ISSUE TITLE
Add Filter Functionality For the Commits Logs 

### ISSUE THREAD

**Issue by AmmarAbouZor** [extrawurst/gitui#1790] opened 2023-08-04 20:19 UTC
**Is your feature request related to a problem? Please describe.**

Searching the commits logs via fuzzy finder was always a really wanted feature that couldn't be achieved without sacrificing the performance since we must load all the commits see #1687 #1752.     

**Describe the solution you'd like**

Instead of using fuzzy finder, we can add a filter function (popup with option to search the commit message, description, Author, date from ...to). 
After applying the filter we can load the commits as chunks then apply the filter and remove the commits that don't meet it and keep polling new chunks of commits until the view is full (like the current logic).
Additionally we need to add an indicator to the commits log view so the users can see that a filter is currently active and keybinding to remove the filter.

At first I would like to know if this idea could be achievable here, since I'm not familiar enough with the internals and if so then we need to define the filter criteria and the filter indicator in the commits log view 

**Additional context**

For Reference here is a journal app with a basic filter function [Tui-Journal](https://github.com/AmmarAbouZor/tui-journal). The Implementation there isn't optimized for performance

**Comment by extrawurst** [comment] 2023-08-05 13:50
duplicate of a handful of issues before. closing in favour of #1791

**Closed by extrawurst** 2023-08-05 13:50 UTC
Labels: feature-request
