### ISSUE TITLE
`cargo install gitui` fails with multiple errors

### ISSUE THREAD

**Issue by kyegupov** [extrawurst/gitui#2222] opened 2024-05-08 16:55 UTC
**Describe the bug**
`cargo install gitui` fails with multiple errors

Seems like the `ratatui` library had a breaking update.

**Screenshots**
```
error[E0308]: mismatched types
    --> /home/$MYSELF/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gitui-0.26.1/src/components/textinput.rs:157:28
     |
157  |                 .set_cursor_line_style(self.theme.text(true, false));
     |                  --------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `ratatui::style::Style`, found a different `ratatui::style::Style`
...
error[E0308]: mismatched types
    --> /home/$MYSELF/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gitui-0.26.1/src/components/textinput.rs:169:6
     |
168  |                   text_area.set_block(
     |                             --------- arguments to this method are incorrect
169  | /                     Block::default()
170  | |                         .borders(Borders::ALL)
171  | |                         .border_style(
172  | |                             ratatui::style::Style::default()
...    |
176  | |                         )
177  | |                         .title(self.title.clone()),
     | |__________________________________________________^ expected `ratatui::widgets::block::Block<'_>`, found `ratatui::widgets::Block<'_>`
...
error[E0277]: the trait bound `impl ratatui::widgets::Widget + '_: Widget` is not satisfied
   --> /home/$MYSELF/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gitui-0.26.1/src/components/textinput.rs:644:20
    |
644 |             f.render_widget(ta.widget(), area);
    |               ------------- ^^^^^^^^^^^ the trait `Widget` is not implemented for `impl ratatui::widgets::Widget + '_`
```

**Context (please complete the following information):**
 - Ubuntu 22.04
 - gitui: whatever cargo downloads, apparently `gitui v0.26.1`
 - Rust stable 1.78.0

**Comment by remique** [comment] 2024-05-08 19:57
This has been adressed before (#2098) and is mentioned in [README](https://github.com/extrawurst/gitui?tab=readme-ov-file#cargo-install).

Using `cargo install gitui --locked` should resolve this issue.

**Comment by extrawurst** [comment] 2024-05-09 07:32
Yes this is a duplicate of #2098

**Closed by extrawurst** 2024-05-09 07:32 UTC
Labels: bug
