### ISSUE TITLE
Add log graph

### ISSUE THREAD

**Issue by felix307253927** [extrawurst/gitui#2412] opened 2024-10-30 09:22 UTC
**Is your feature request related to a problem? Please describe.**

I would like a log viewing feature similar to git graph, as shown in the screenshot below

**Describe the solution you'd like**
Add a graph of the branch in the log module

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/c17cd049-7c34-4a10-8a12-e0598638d996)

**Comment by extrawurst** [comment] 2024-10-30 09:54
duplicate of #81

**Closed by extrawurst** 2024-10-30 09:54 UTC
Labels: feature-request
