### ISSUE TITLE
Gitui considers my repository bare, despite the fact that it is not.

### ISSUE THREAD

**Issue by Icantjuddle** [extrawurst/gitui#1629] opened 2023-03-30 15:36 UTC
**Describe the bug**
`gitui` bails telling me my repo is bare despite the fact that it is not.

**To Reproduce**
`gitui` in my git repo.

**Expected behavior**
Starts up as expected.

**Screenshots**

```
❯ git config --get core.bare
false
❯ gitui
Error: invalid path
please run gitui inside of a non-bare git repository
```

#### Software version

gitui 0.22.1

#### Operating system

Linux 5.8.0-59-generic

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=kak
GIT_EDITOR=<not set>
VISUAL=kak
```

#### Command-line

```bash
gitui --bugreport 'considers this a bare repo'
```

**Comment by extrawurst** [comment] 2023-03-31 16:42
Any idea how I can reproduce this?

**Comment by Icantjuddle** [comment] 2023-03-31 20:08
To be honest, I'm not sure. 

I cloned `microsoft/STL` and ran `gitui` there to try and repro in a public repository. But when I run `gitui` there I get `Error: receiving on an empty and disconnected channel` and `gitui` exits immediately.

**Comment by fcs-ts** [comment] 2023-04-03 19:45
@Icantjuddle what does `git status` say? I remeber getting this error when trying to run `gitui` on folders with _weird_ permissions

**Comment by Icantjuddle** [comment] 2023-04-11 14:06
`git status` runs normally. I think the folder has normal perms:

```
❯ gitui
Error: receiving on an empty and disconnected channel
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
❯ stat .
  File: .
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d    Inode: 79744913    Links: 13
Access: (0775/drwxrwxr-x)  Uid: (1889600450/   bjudd)   Gid: (1889600450/   bjudd)
Access: 2023-04-11 00:20:01.337908019 -0700
Modify: 2023-03-31 13:02:38.663453363 -0700
Change: 2023-03-31 13:02:38.663453363 -0700
 Birth: -
❯ stat .git
  File: .git
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d    Inode: 79744924    Links: 9
Access: (0775/drwxrwxr-x)  Uid: (1889600450/   bjudd)   Gid: (1889600450/   bjudd)
Access: 2023-04-11 07:01:30.379831433 -0700
Modify: 2023-04-11 07:01:48.591808693 -0700
Change: 2023-04-11 07:01:48.591808693 -0700
 Birth: -
```

**Comment by fabiangeisler** [comment] 2023-05-12 09:07
Hi!
I see that issue as well for repositories that live on a network drive. Repos on my local machine work as intended with `gitui`. 
I am on CentOS 7 and have the same gitui version. 
Let me know if you need more info.

**Comment by Icantjuddle** [comment] 2023-05-16 14:07
I've reinstalled from `cargo` and confirmed that it exits as above; however, I built `gitui` from source on commit `aa4266cd1f8ffda4c38b86e342ae3b9b38300f25` and it doesn't have the above issue. So not sure what happened, but sounds like I won't have this issue on the next release.

**Comment by pm100** [comment] 2023-05-22 09:26
@extrawurst - i noticed that any error opening the repo causes this, an invalid config file produced it for me, git complains explitly but gitui produces this error

```
pm100@pauls-MacBook-Air libgit2 % gitui
Error: invalid path
please run gitui inside of a non-bare git repository
pm100@pauls-MacBook-Air libgit2 % git status
fatal: bad config line 3 in file /Users/pm100/mygit
pm100@pauls-MacBook-Air libgit2 % git status
```

**Comment by Hpmason** [comment] 2023-06-20 19:10
Looks like this is the probably the same problem as #1293 if the problem was occurring on a network/mounted drive. It does appear to be fixed in the newest commit on master, but the latest crates.io release still isn't fixed. For anyone still running into this issue try installing gitui from master:

```
cargo install --git https://github.com/extrawurst/gitui
```

**Comment by fabiangeisler** [comment] 2023-08-28 07:58
FYI: This is now fixed for me in the latest gitui release v0.24.0.

**Closed** 2023-08-28 08:03 UTC
Labels: bug

**Comment by rdstevens-gh** [comment] 2025-04-07 13:09
I'm still having this problem, as of gitui 0.27.0 2025-01-14 (99f6967)

**Comment by extrawurst** [comment] 2025-04-07 13:12
@rdstevens-gh do you have a repo to reproduce?

**Comment by rdstevens-gh** [comment] 2025-04-07 13:15
I've just tried gitui on several of our other repos (all Azure DevOps hosted). Gitui isn't working on any of them - and they don't use git lfs or anything out of the ordinary.

**Comment by extrawurst** [comment] 2025-04-07 13:19
Not working meaning they are reported as bare?

**Comment by rdstevens-gh** [comment] 2025-04-07 13:52
Solution found!

Running: gitui -l gave the following log entry:

13:43:38 [ERROR] repo open error: repository path [REDACTED] is not owned by current user; class=Config (7); code=Owner (-36)

This is a git error. My directory isn't trusted/safe, for some reason. (I don't know why this would be, given that I cloned this repo using my current user.)

The Fix:

git config --global --add safe.directory *

This adds the [safe] section to the user-scoped git config (global to all repos accessed by this user account), and adds the directory = * key/value.

For security, it might be better NOT to use the * wildcard, however for my use-case * is fine, and works!

**Comment by rdstevens-gh** [comment] 2025-04-07 14:01
Done here: https://github.com/gitui-org/gitui/issues/2599
