### ISSUE TITLE
Error during compile: undefined reference to `git_branch_name_is_valid'

### ISSUE THREAD

**Issue by BuriedStPatrick** [extrawurst/gitui#883] opened 2021-08-29 13:23 UTC
**Describe the bug**
Installation of GitUI v0.17 via Cargo seems to break during compile. I am running the latest stable version of rust using the `rustup` toolchain install via: `rustup toolchain install stable`. It doesn't appear to be an issue with previous versions.

**To Reproduce**
1. Run `cargo install --git https://github.com/extrawurst/gitui --tag v0.17`

**Expected behavior**
Compiles `gitui` and installs inside `~/.cargo/bin`.

**Actual behavior**
Throws an ``error: linking with `cc` failed: exit status: 1.`` See **Additional context** for build log.

**Context (please complete the following information):**
 - OS + Version: `Linux Archcraft, Kernel: 5.13.13-arch1-1`
 - GitUI Version: `0.17.0`
 - Rust version: `1.54.0`
 
**Additional context**
Build log:
```
~ cargo install --git https://github.com/extrawurst/gitui --tag v0.17
    Updating git repository `https://github.com/extrawurst/gitui`
  Installing gitui v0.17.0 (https://github.com/extrawurst/gitui?tag=v0.17#70e1e310)
    Updating crates.io index
   Compiling libc v0.2.101
   Compiling autocfg v1.0.1
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.28
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.75
   Compiling memchr v2.4.1
   Compiling pkg-config v0.3.19
   Compiling log v0.4.14
   Compiling serde_derive v1.0.130
   Compiling serde v1.0.130
   Compiling scopeguard v1.1.0
   Compiling bitflags v1.3.2
   Compiling lazy_static v1.4.0
   Compiling crossbeam-utils v0.8.5
   Compiling unicode-width v0.1.8
   Compiling tinyvec_macros v0.1.0
   Compiling matches v0.1.9
   Compiling regex-syntax v0.6.25
   Compiling crossbeam-epoch v0.9.5
   Compiling parking_lot_core v0.8.5
   Compiling signal-hook v0.3.9
   Compiling proc-macro-hack v0.5.19
   Compiling adler v1.0.2
   Compiling ryu v1.0.5
   Compiling smallvec v1.6.1
   Compiling percent-encoding v2.1.0
   Compiling unicode-bidi v0.3.6
   Compiling crc32fast v1.2.1
   Compiling rayon-core v1.9.1
   Compiling serde_json v1.0.67
   Compiling safemem v0.3.3
   Compiling base64 v0.13.0
   Compiling hashbrown v0.11.2
   Compiling bit-vec v0.6.3
   Compiling xml-rs v0.8.4
   Compiling same-file v1.0.6
   Compiling anyhow v1.0.43
   Compiling openssl-probe v0.1.4
   Compiling either v1.6.1
   Compiling gimli v0.25.0
   Compiling linked-hash-map v0.5.4
   Compiling itoa v0.4.8
   Compiling bugreport v0.4.1
   Compiling cassowary v0.3.0
   Compiling fnv v1.0.7
   Compiling unicode-segmentation v1.8.0
   Compiling smawk v0.3.1
   Compiling lazycell v1.3.0
   Compiling shell-escape v0.1.5
   Compiling rustc-demangle v0.1.21
   Compiling easy-cast v0.4.4
   Compiling bytesize v1.1.0
   Compiling instant v0.1.10
   Compiling lock_api v0.4.5
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling memoffset v0.6.4
   Compiling miniz_oxide v0.4.4
   Compiling indexmap v1.7.0
   Compiling tinyvec v1.3.1
   Compiling textwrap v0.11.0
   Compiling unicode-truncate v0.2.0
   Compiling form_urlencoded v1.0.1
   Compiling line-wrap v0.1.1
   Compiling bit-set v0.5.2
   Compiling walkdir v2.3.2
   Compiling itertools v0.10.1
   Compiling yaml-rust v0.4.5
   Compiling clap v2.33.3
   Compiling addr2line v0.16.0
   Compiling unicode-normalization v0.1.19
   Compiling aho-corasick v0.7.18
   Compiling object v0.26.2
   Compiling scopetime v0.1.1 (/home/patrick/.cargo/git/checkouts/gitui-5ccde44ba6d0b40a/70e1e31/scopetime)
   Compiling time v0.1.43
   Compiling signal-hook-registry v1.4.0
   Compiling mio v0.7.13
   Compiling num_cpus v1.13.0
   Compiling dirs-sys-next v0.1.2
   Compiling which v4.2.2
   Compiling quote v1.0.9
   Compiling jobserver v0.1.24
   Compiling crossbeam-channel v0.5.1
   Compiling regex v1.5.4
   Compiling idna v0.2.3
   Compiling parking_lot v0.11.2
   Compiling dirs-next v2.0.0
   Compiling cc v1.0.69
   Compiling flate2 v1.0.20
   Compiling signal-hook-mio v0.2.1
   Compiling url v2.2.2
   Compiling fancy-regex v0.7.1
   Compiling crossbeam-deque v0.8.1
   Compiling openssl-src v111.16.0+1.1.1l
   Compiling chrono v0.4.19
   Compiling libz-sys v1.1.3
   Compiling openssl-sys v0.9.66
   Compiling libssh2-sys v0.2.21
   Compiling sys-info v0.9.0
   Compiling libgit2-sys v0.12.22+1.1.0
   Compiling backtrace v0.3.61
   Compiling simplelog v0.10.0
   Compiling unicode-linebreak v0.1.2
   Compiling thiserror-impl v1.0.28
   Compiling git-version-macro v0.3.5
   Compiling git-version v0.3.5
   Compiling thiserror v1.0.28
   Compiling filetreelist v0.2.0 (/home/patrick/.cargo/git/checkouts/gitui-5ccde44ba6d0b40a/70e1e31/filetreelist)
   Compiling textwrap v0.14.2
   Compiling crossterm v0.20.0
   Compiling bincode v1.3.3
   Compiling plist v1.2.1
   Compiling ron v0.6.4
   Compiling tui v0.16.0
   Compiling syntect v4.6.0
   Compiling git2 v0.13.21
   Compiling asyncgit v0.17.0 (/home/patrick/.cargo/git/checkouts/gitui-5ccde44ba6d0b40a/70e1e31/asyncgit)
   Compiling gitui v0.17.0 (/home/patrick/.cargo/git/checkouts/gitui-5ccde44ba6d0b40a/70e1e31)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/cargo-installIGthF9/release/deps/gitui-8fdd7bbcc60e53bb.gitui.crixscyd-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installIGthF9/release/deps" "-L" "/usr/lib" "-L" "/tmp/cargo-installIGthF9/release/build/libssh2-sys-4565c7625ea1816f/out/build" "-L" "/tmp/cargo-installIGthF9/release/build/openssl-sys-e44d916ec27348ff/out/openssl-build/install/lib" "-L" "/tmp/cargo-installIGthF9/release/build/sys-info-aa9125d87b5ebf51/out" "-L" "/home/patrick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcx4EABP/libsys_info-fbb1f3177c092ef8.rlib" "/tmp/rustcx4EABP/liblibssh2_sys-bd716511dba4fd29.rlib" "/tmp/rustcx4EABP/libopenssl_sys-c3715f5e6d6063a2.rlib" "-Wl,--start-group" "-Wl,--end-group" "/home/patrick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d6c7a399d95d173f.rlib" "-Wl,-Bdynamic" "-lgit2" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/patrick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installIGthF9/release/deps/gitui-8fdd7bbcc60e53bb" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /tmp/cargo-installIGthF9/release/deps/gitui-8fdd7bbcc60e53bb.gitui.crixscyd-cgu.0.rcgu.o: in function `gitui::app::App::draw_popups':
          gitui.crixscyd-cgu.0:(.text._ZN5gitui3app3App11draw_popups17h1ae8b2c178037900E+0x3708): undefined reference to `git_branch_name_is_valid'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: failed to compile `gitui v0.17.0 (https://github.com/extrawurst/gitui?tag=v0.17#70e1e310)`, intermediate artifacts can be found at `/tmp/cargo-installIGthF9`

Caused by:
  could not compile `gitui`

To learn more, run the command again with --verbose.
```

**Comment by zcorniere** [comment] 2021-08-29 14:35
Look like a duplicate of #853

**Comment by extrawurst** [comment] 2021-08-29 18:39
Indeed a duplicate

**Closed** 2021-09-02 16:58 UTC
