### ISSUE TITLE
It should support auto login for push 

### ISSUE THREAD

**Issue by computerphilosopher** [extrawurst/gitui#800] opened 2021-06-30 15:40 UTC
**Is your feature request related to a problem? Please describe.**
When I use git command, I don't have to type the user name and password  everytime for push. Because I saved my password by [credential helper](https://stackoverflow.com/questions/11403407/git-asks-for-username-every-time-i-push). 

**Describe the solution you'd like**
If the user is using a credential helper feature, the gitui should not ask a user name and password

**Comment by extrawurst** [comment] 2021-06-30 16:31
I suggest using a ssh key to solve that:
* more secure
* more convenient

https://docs.github.com/en/github-ae@latest/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by alippai** [comment] 2021-07-01 21:17
GitHub recommends HTTPS instead of SSH:
https://docs.github.com/en/get-started/quickstart/set-up-git#next-steps-authenticating-with-github-from-git

**Comment by extrawurst** [comment] 2021-07-01 21:23
> it can't be easily dismissed as SSH is not the defacto or superior solution right now

I am not dismissing https, just my personal suggestion.

speaking of which, it seems GitHub changed their *recommendation* a few times: https://stackoverflow.com/questions/11041729/why-does-github-recommend-https-over-ssh

**Comment by alippai** [comment] 2021-07-01 21:39
Yes, I was laughing at that when tried to collect info on this topic. I'm sorry if I implied you already dismissed the idea, it wasn't my intention. I totally agree with your personal suggestion.

**Comment by tmpgnh** [comment] 2021-07-02 13:40
My personal preference is SSH as well but I have to work with HTTPS-only repos too.

**Comment by skyfaller** [comment] 2021-10-01 12:40
No, not stale bot! My least favorite thing about GitHub. People not talking about a bug is better than people spamming low-effort comments. Just because people aren't talking about a bug doesn't mean they have stopped caring about it. Just because the people who care about the bug lack the coding chops to fix it doesn't mean it should be closed.

It's interesting, this bug has made me switch entirely to SSH keys for git, which apparently brings me in line with extrawurst's opinions on HTTPS vs. SSH, but I think leaving this bug unfixed would not be a very nice way of winning that debate. If people prefer HTTPS for whatever reason, gitui should support that relatively common workflow.

**Comment by extrawurst** [comment] 2021-10-01 12:54
@skyfaller the thing is: as long as no one picks this up it will not happen. and it being dormant that long is a good indicator no  one cares enough about it. I certainly will not have time to fix it in the foreseeable future. and *closed* is not *deleted* the info is still here to point to for future reference

**Comment by skyfaller** [comment] 2021-10-01 13:18
But my understanding of "closed" on a big is that

- the problem has been fixed, or
- the problem cannot be fixed (e.g. upstream bug), or
- the author does not want it to be fixed

If stale bot runs around closing bugs willy nilly, now the closed state doesn't mean much of anything. The difference between a closed bug and an open bug can just be happenstance, or the confluence of tangential factors such as:

- Was the nature of the bug obvious? How much discussion was required before everyone understood it? Longer discussions mean more time before stale bot triggers. I think obvious bugs may sometimes be higher priority to fix.
- How many annoying users who like to complain did this issue affect? This gives incentives to users who care about the bug to be whiny, rather than wait patiently. It also fills my GitHub notifications with stale bot and people defending against stale bot, which now that I think about it may be the core of my grudge against stale bot. I certainly comment on any stale botted issue I follow, purely because I hate stale bot, but this is a little like emailing a large email thread asking to be removed because you're getting too many email notifications. Now we all must suffer.
- Did the person with the time and energy to fix it show up in 3 months or 6 months? This is an arbitrary matter of timing, and says nothing about the bug itself.

In my last confrontation with stale bot, me and the other user who cared about the bug eventually found someone to work on fixing it... But the bug is still closed! https://github.com/yuin/goldmark/issues/180 "Closed" doesn't even mean that the bug is inactive, that nobody is working on it!

Anyway, sorry for hijacking the discussion on this issue to make it less stale, I can open a bug requesting the demise of stale bot instead ;-)

**Comment by W1M0R** [comment] 2021-11-26 02:28
Support for git credential helpers will be a useful addition to an already very useful tool. From what I can imagine, the `git config credential.helper` command will indicate which credential helper is set up (e.g. https://github.com/Luzifer/git-credential-vault), and then the relevant input could be piped to the helper. I'm not sure how this would work with [built-in helpers](https://git-scm.com/docs/gitcredentials) (`store` and `cache`).

**Comment by extrawurst** [comment] 2022-01-22 17:49
@computerphilosopher credential.helper should actually be honoured. can you share your configuration as an example so I can try to reproduce it?

**Comment by extrawurst** [comment] 2022-01-23 00:17
would be great if you could build from source off of branch `creds-helper-800` see #1091 - it should honour built-in `store` credential helper now. it expects the credentials to be set already though.

essentially if you can retrieve your credentials via `printf "protocol=https\nhost=github.com\n" | git credential-store get` then gitui should be able to as swell.

**Comment by jgoldhammer** [comment] 2022-01-23 13:08
I have tried the branch and build it 
The command from the discussion

`printf "protocol=https\nhost=github.com\n" | git credential fill`

works perfectly.

![image](https://user-images.githubusercontent.com/3872101/150679815-eedf59ec-dea9-474b-a2a5-dd624c56855a.png)


The mentioned command here in the merge request

`printf "protocol=https\nhost=github.com\n" | git credential-store get`

does not work on my machine.
![image](https://user-images.githubusercontent.com/3872101/150679949-1fb8ff37-2359-4270-a5df-e40e282cbdc5.png)


When using gitui I see following output in the log ( bat $HOME/Library/Caches/gitui/gitui.log)

![image](https://user-images.githubusercontent.com/3872101/150679892-90b080e8-8755-49bd-b681-88e97fead740.png)

**Comment by extrawurst** [comment] 2022-01-23 14:34
@jgoldhammer can you check if `printf ... | git credential-osxkeychain get` works? (you were on macOS right?)

**Comment by jgoldhammer** [comment] 2022-01-23 14:46
Yes, I am on macos...

This call works for known and unknown credentials - the script always returns.

`printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain get`

![image](https://user-images.githubusercontent.com/3872101/150683980-17e0ae24-c1fd-441a-99a0-97c176fe8396.png)

`printf "protocol=https\nhost=github1.com\n" | git credential-osxkeychain get` 

![image](https://user-images.githubusercontent.com/3872101/150684068-a02b9154-6762-4fd4-b25d-28a1387d165d.png)

(Please ignore the alias hint - it is printed by fish shell)

**Comment by extrawurst** [comment] 2022-01-23 17:13
@jgoldhammer can you test something? it turns out `credentials.helper` should have been supported already on the `main` branch. can you make sure your credential helper is configured to use osxkeychain via: `git config credential.helper osxkeychain` inside your repo you want to test in. I need to investigate deeper

**Comment by jgoldhammer** [comment] 2022-01-23 20:35
I can make sure that the credential helper is configured this way, but gitui still asks for the username and password.

**Comment by extrawurst** [comment] 2022-01-23 23:18
@jgoldhammer ok please try this PRs branch again. turns out the config lookup for the helper to use was not checking the repo config, only the system git config. now we should get it to work.

with master it should work if you set this config via `git config --global credential.helper osxkeychain` (in `~/.gitconfig`)

if this looks good to you I would close this ticket and create a followup:
* try more ways to be able to call `git credential fill`, cause that would not require any such explicit helper to be set

**Closed** 2022-01-23 23:36 UTC
Labels: enhancement

**Comment by jgoldhammer** [comment] 2022-01-24 06:47
Master works perfectly after setting the credential helper globally with the above command!

Thanks for making it possible 🥳

**Comment by Byron** [comment] 2022-09-18 01:55
> @jgoldhammer ok please try this PRs branch again. turns out the config lookup for the helper to use was not checking the repo config, only the system git config. now we should get it to work.
> 
> with master it should work if you set this config via `git config --global credential.helper osxkeychain` (in `~/.gitconfig`)
> 
> if this looks good to you I would close this ticket and create a followup:
> 
> * try more ways to be able to call `git credential fill`, cause that would not require any such explicit helper to be set

I ran into the same problem, that is that credential helpers are configured via built-in configuration that differs depending on the platform which makes custom configuration of these necessary - something I thought should be avoidable.

`gitoxide` has two solutions for this. The first probably isn't viable for this project as it simply calls the actual `git credential` program which will automatically pick up the special configuration of the git installation.

The second solution is to [run the git binary](https://github.com/Byron/gitoxide/blob/535e967666c6da657ff1b7eff7c64ab27cafb182/git-repository/src/env.rs#L30-L87) to extract the special path and place it first into the list of loaded configuration files. If that is possible with `libgit2`, I think a version of the linked code could help here, too, to make everything work without requiring to configure anything, on any platform.

**Comment by paaloeye** [comment] 2025-02-17 00:40
```shell
sudo git config --system credential.helper osxkeychain
```

is the move here if you're syncing dotfiles across different operating systems, e.g. `Windows` and `MacOS`

It's worth noting that `sudo` here is **required** due to `/etc/gitconfig` file
