### ISSUE TITLE
Gitui slow start-up

### ISSUE THREAD

**Issue by eve-cxrp** [extrawurst/gitui#1239] opened 2022-06-21 11:37 UTC
**Describe the bug**
I have a repository where the start-up of gitui is slow. 

**To Reproduce**
Unfortunately I cannot share the repository because it is confidential. 

**Expected behavior**
Fast start-up

**Screenshots**
![gitui](https://user-images.githubusercontent.com/80681009/174789924-d677c85b-3ae5-43c5-a543-07706071aa31.gif)

**Context:**
gitui v0.20.1 installed via homebrew
MacOS 12.3.1 on a MacBook Pro Apple M1

**Additional context**
This repo is quite huge and has also a lot of submodules and sub-submodules

**Comment by extrawurst** [comment] 2022-08-28 11:28
probably a duplicate of https://github.com/extrawurst/gitui/issues/523

**Closed** 2022-08-28 11:29 UTC
Labels: duplicate

**Comment by extrawurst** [comment] 2022-09-01 21:53
please checkout https://github.com/extrawurst/gitui/pull/1310
