### ISSUE TITLE
Theme file not loading on macOS

### ISSUE THREAD

**Issue by maxhoffmann** [extrawurst/gitui#2007] opened 2024-01-12 10:29 UTC
**Describe the bug**
When I override the default theme or try to add a new one, it doesn’t affect `gitui`’s theme.

**To Reproduce**
1. Install `gitui` via `brew`
2. Add a theme at `~/.config/gitui/theme.ron`
3. Example theme:
```ron
(
    line_break: Some(""),
    selection_bg: Some(LightBlue),
)
```
4. Open `gitui`
5. Colors are still the same and new line operator is still visible.

**Expected behavior**
I expect the theme to change.

**Context (please complete the following information):**
 - OS/Distro + Version: macOS `13.6.3`
 - GitUI Version `0.24.3`

**Additional context**
It would help to see where themes are loaded from, in case gitui doesn’t use `~/.config/gitui/`. Trying to add a custom theme and loading it via `-t` also doesn’t lead to any error. It silently fails, so I cannot debug where the `gitui` loads the themes from.

**Comment by extrawurst** [comment] 2024-01-12 12:28
just tried and on master aswell on the version you use via brew exactly your theme changes work as expected.

**Comment by maxhoffmann** [comment] 2024-01-12 12:57
@extrawurst Is there any way to tell gitui that it should log which themes it loads and in which folder it looks? This would really help debugging this on my machine.

**Comment by extrawurst** [comment] 2024-01-12 13:19
please run with `-l` to enable logging, see https://github.com/extrawurst/gitui#diagnostics

and share the log created. also helpful is checking if `echo $HOME` and `echo ~` return the right user folder where you store the config

**Comment by extrawurst** [comment] 2024-02-18 13:04
@maxhoffmann still an issue? any findings via the log option?

**Comment by maxhoffmann** [comment] 2024-02-18 14:16
@extrawurst unfortunately yes. there are no entries in the log file about loading a config. `echo $HOME` and `echo ~` return the correct path

**Comment by extrawurst** [comment] 2024-02-19 11:54
@maxhoffmann can you please try to build from source? in be10d9096a93b030ec3f1ab776a21225d974e272 I added logging theme loading errors to the logfile

**Comment by extrawurst** [comment] 2024-02-19 20:35
@cgahr please try again with current master (f0f90a8) which should also print the path of the theme that errors

**Comment by cgahr** [comment] 2024-02-20 06:33
I can confirm the `-t <path>` and `--theme <path>` both have no effect.

To reproduce:
1. remove last `)` from `~/.config/gitui/theme.ron` so that the resulting file is not a valid configuration
2. run `./target/debug/gitui -l -t doesnotexist`

The relevant line in the log file is 
```
06:31:53 [ERROR] theme error ["/home/cgahr/.config/gitui/theme.ron"]: 28:1: Unexpected end of RON
```
As you can see, gitui is complaining that the config is not valid (which it is not because I broke it), however, it is reading the wrong config file.

**Comment by extrawurst** [comment] 2024-02-20 14:29
i think i know where the confustion comes from. the provided parameter is a filename, not a path. right now you cannot change the path but only the filename that's loaded from the config path.

**Comment by extrawurst** [comment] 2024-02-20 14:32
please test the version in the PR #2077

**Comment by cgahr** [comment] 2024-02-20 15:23
I see, that explains why I wasn't able to change the theme, it was not in the config folder!
I can confirm that `-t <file-in-config-dir>` works as intended then.

However, #2077 doesn't work correctly, I don't get a log entry if I try to use a nonexistent theme.

**Comment by cgahr** [comment] 2024-02-20 17:32
I can confirm, at da610e7 every works now correctly. I think you can close this issue.

**Closed** 2024-02-20 17:52 UTC
Labels: bug, help wanted

**Comment by sainttttt** [comment] 2024-08-26 19:39
> **Describe the bug** When I override the default theme or try to add a new one, it doesn’t affect `gitui`’s theme.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install `gitui` via `brew`
> 2. Add a theme at `~/.config/gitui/theme.ron`
> 3. Example theme:
> 
> ```ron
> (
>     line_break: Some(""),
>     selection_bg: Some(LightBlue),
> )
> ```
> 
> 4. Open `gitui`
> 5. Colors are still the same and new line operator is still visible.
> 
> **Expected behavior** I expect the theme to change.
> 
> **Context (please complete the following information):**
> 
> * OS/Distro + Version: macOS `13.6.3`
> * GitUI Version `0.24.3`
> 
> **Additional context** It would help to see where themes are loaded from, in case gitui doesn’t use `~/.config/gitui/`. Trying to add a custom theme and loading it via `-t` also doesn’t lead to any error. It silently fails, so I cannot debug where the `gitui` loads the themes from.

I had this same issue too and the way I fixed it was changing 

```
    selection_bg: Some(LightBlue),
```

to 

```
    selection_bg: Some("LightBlue"),
```
