### ISSUE TITLE
crash by typing right arrow in Stashes

### ISSUE THREAD

**Issue by Dubhead** [extrawurst/gitui#178] opened 2020-07-07 00:57 UTC
**Describe the bug**

Typing right arrow in Stashes crashes gitui

**To Reproduce**

1. Git-clone the gitui repository
2. `echo foo >> README.md`
3. `git stash`
4. Start `gitui`
5. Type `4` for `Stashes` screen
6. Type the right arrow key

**Expected behavior**

The stash content should be displayed.

**Screenshots**

```
% git stash list
stash@{0}: WIP on master: 59d93d7 cargo update
% gitui
panic: PanicInfo { payload: Any, message: Some(failed to fetch: Git(Error { code: -1, klass: 0, message: "parent index out of bounds" })), location: Location { file: "/home/miura/.cargo/registry/src/github.com-1ecc6299db9ec823/asyncgit-0.8.0/src/commit_files.rs", line: 74, col: 13 } }
trace:
   0: gitui::set_panic_handlers::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:111
   4: core::option::expect_none_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/option.rs:1268
   5: core::result::Result<T,E>::expect
   6: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys/unix/thread.rs:87
  10: start_thread
  11: __clone

panic: Any
trace:
   0: gitui::set_panic_handlers::{{closure}}
   1: rayon_core::registry::Registry::handle_panic
   2: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
   3: std::sys_common::backtrace::__rust_begin_short_backtrace
   4: core::ops::function::FnOnce::call_once{{vtable.shim}}
   5: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys/unix/thread.rs:87
   6: start_thread
   7: __clone

[1]    12241 abort (core dumped)  gitui
%
```

**Context (please complete the following information):**

- OS: Linux x86_64 (Fedora 32 Workstation with latest updates)
- GitUI Version: 0.8.0
- Rust version: 1.44.1

**Additional context**

**Comment by extrawurst** [comment] 2020-07-07 07:11
@Dubhead thanks for reporting this, there seems to be a subtle difference in how `git stash` and `libgit2` create a stash commit. `libgit2` seems to always create the third parent necessary to stash untracked files and `git stash` skips that step when there are no untracked files to stash. this is the root cause for the crash. will be fixed

**Closed** 2020-07-07 07:12 UTC

**Comment by Dubhead** [comment] 2020-07-07 08:35
Thanks for the fix!
