### ISSUE TITLE
View log at git revision

### ISSUE THREAD

**Issue by M1cha** [extrawurst/gitui#1600] opened 2023-03-14 12:44 UTC
**Is your feature request related to a problem? Please describe.**
Currently you can only view the log of HEAD, tags, branches and stashes. But I can't enter an arbitrary git hash or an alias(like FETCH_HEAD).

**Describe the solution you'd like**
Either add a form for pasting a revision or alias, or accept a position argument to `gitui` similar to the way `git log REV` works.

**Comment by extrawurst** [comment] 2023-03-14 12:51
well actually if its about the detail view of a specific commit:
<img width="1624" alt="Screenshot 2023-03-14 at 13 50 43" src="https://user-images.githubusercontent.com/776816/225006183-3350b48e-760b-4329-a94a-7a407f946dbc.png">

that could be done 🧐 its only a problem if you want to jump to that commit in the log view if its not in the current branch lineage

**Comment by M1cha** [comment] 2023-03-14 12:57
Yea and that's exactly what I want to do :D 
I guess I also misinterpreted the menu in the log view since I expected those to be for viewing and not for switching. Both are obviously useful features for gitui, the question is just if one would expect modifying options within the log view :thinking:

**Comment by extrawurst** [comment] 2023-03-14 12:59
> Yea and that's exactly what I want to do :D

then its more like a dupe of #506 

> I guess I also misinterpreted the menu in the log view since I expected those to be for viewing and not for switching

can you specify?

**Comment by extrawurst** [comment] 2023-08-22 13:57
#1818 will deal with the go-to-sha-in-the-current-log part.
a follow-pr could figure out that a sha is in the repo but not in the current log and just open the commit details view for that one as a popup

**Comment by extrawurst** [comment] 2024-02-11 18:05
solved via #1818

**Closed by extrawurst** 2024-02-11 18:05 UTC
Labels: feature-request
