### ISSUE TITLE
Panel shortcuts have disappeared in v0.13.0

### ISSUE THREAD

**Issue by savchenko** [extrawurst/gitui#614] opened 2021-04-05 02:52 UTC
**Describe the bug**
Panel shortcuts have disappeared in v0.13.0, they were still present in v0.13.0-RC.

**To Reproduce**
1. Open `gitui`.
2. Try to quickly switch between staged and unstaged changes on the first screen.
3. Fiasco.

**Expected behavior**
There are hotkeys to quickly flick between the panels in any given screen.

**Screenshots**

RC, hotkeys are still there:
![](https://raw.githubusercontent.com/extrawurst/gitui/v0.13.0-rc1/assets/pull.gif)

Release, hotkeys are gone:
![](https://raw.githubusercontent.com/extrawurst/gitui/v0.13.0/assets/by-line-ops.gif)

**Context (please complete the following information):**
 - OS/Distro + Version: Debian 11.
 - GitUI Version: v0.13.0 and v0.13.0-RC
 - Rust version: N/A, using pre-built binaries from GitHub.

**Additional context**

**Comment by extrawurst** [comment] 2021-04-05 07:30
Duplicate of #594

**Closed** 2021-04-05 07:30 UTC
