### ISSUE TITLE
[Help] Shortcut issues

### ISSUE THREAD

**Issue by hgezim** [extrawurst/gitui#1295] opened 2022-08-24 15:29 UTC
How do I jump from one hunk to next without visiting each line? I'm SSH-ed into a Linux machine where `gitui` runs from a Mac.

**Comment by hgezim** [comment] 2022-08-24 15:35
I'm having more shortcut troubles. Pressing <enter> doesn't add hunk but the whole file:

A video: https://share.cleanshot.com/EVN9Yy

**Comment by extrawurst** [comment] 2023-01-23 09:48
for some reason it shows that you only have one hunk in the diff. that's why `enter` adds the whole file. need to figure out how to reproduce this

**Comment by extrawurst** [comment] 2023-01-23 09:48
also related to #1523

**Comment by extrawurst** [comment] 2023-08-12 15:37
duplicate of #1523

**Closed by extrawurst** 2023-08-12 15:37 UTC
Labels: bug, dormant
