### ISSUE TITLE
PATH not respected in hooks

### ISSUE THREAD

**Issue by Lykos153** [extrawurst/gitui#1967] opened 2023-12-01 11:40 UTC
**Describe the bug**
I use [devenv](https://devenv.sh) and [direnv](https://direnv.net) to make some applications available on a per-directory basis by setting the PATH environment variable. I use it especially to provide project specific git hooks. However, when committing with gitui, those applications don't seem to be available.

**To Reproduce**
1. Create a script somewhere, lets call it `my-own-script`
2. Add its parent to the `PATH`
3. Create a pre-commit hook that uses `my-own-script`
4. Try to commit using gitui
5. See it fail because it can't find `my-own-script`

**Expected behavior**
gitui being able to see applications in the PATH

**Context (please complete the following information):**
 - NixOS unstable
 - gitui 0.24.3

**Comment by extrawurst** [comment] 2023-12-01 12:18
that is so weird. we use https://doc.rust-lang.org/std/process/struct.Command.html#method.new and it is supposed to inherit the parents env

**Comment by extrawurst** [comment] 2023-12-03 23:12
@Lykos153 can you export your environment in your hook for debug purposes like you see it happening in the referenced unittest. I cannot reproduce your problem

**Comment by Lykos153** [comment] 2023-12-05 13:29
Thank you very much for looking into it! And you're right. I realized that with zsh it is indeed working as expected. It only seems to happen using nushell. But what's strange is that it works with git but not with gitui. Whats the difference in how both call the hook? See https://asciinema.org/a/jXDeNAlsYFHs6TSlALE6KGDnr 

I will ask the nushell folks, too.

**Comment by extrawurst** [comment] 2023-12-05 13:37
very strange indeed. i am not using nushell. it seems for some reason the gitui process does not see the new version of the env

**Comment by extrawurst** [comment] 2024-02-11 18:07
closing in case we find new evidence

**Closed by extrawurst** 2024-02-11 18:07 UTC
Labels: bug, help wanted
