### ISSUE TITLE
Revert file changes from a commit picked from the log

### ISSUE THREAD

**Issue by andresovela** [extrawurst/gitui#1075] opened 2022-01-11 11:22 UTC
**Is your feature request related to a problem? Please describe.**
I mistakenly committed some changes some time ago and I would like to revert them. A common thing I used to do with Sourcetree was to find the commit in question, right click on the file and select revert changes or something like that.

See relevant post in StackOverflow: https://stackoverflow.com/questions/2620775/revert-changes-to-a-file-in-a-commit

**Describe the solution you'd like**
It would be nice to be able to navigate to the files view of a commit in the log tab, select the file and have an option to revert the changes to that file.

**Describe alternatives you've considered**
None.

**Comment by extrawurst** [comment] 2022-01-11 14:17
Duplicate of #927 right? It will be in the next release. Can you build from source and test if it works as expected?

**Comment by andresovela** [comment] 2022-01-11 15:50
Ah sorry, I did search for similar issues but I filtered by open issues :D

#927 seems to address reverting the entire commit? I'd be interested in reverting the changes in a particular file in a given commit, rather than reverting all the changes in all files in that commit. I haven't tested from source but from the issue description that's what it sounds like

**Comment by andresovela** [comment] 2022-01-11 15:52
Ah but I guess you can also discard the changes of the files that you don't want to revert, so I guess in a way this is already fixed :)

**Comment by extrawurst** [comment] 2022-01-25 19:46
released as 0.20 now

**Closed by extrawurst** 2022-01-25 19:46 UTC
Labels: duplicate
