### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by yurivict** [extrawurst/gitui#2226] opened 2024-05-16 03:16 UTC
**Describe the bug**
I tried to build using ```cargo install gitui``` and it failed.

See the screenshot:
![image](https://github.com/extrawurst/gitui/assets/271906/a3667739-e41a-491c-ba6b-8158e1ae7d8e)

**To Reproduce**
1. cargo install gitui

**Context (please complete the following information):**
 - OS/Distro + Version: Linux
 - GitUI Version n/a
 - Rust version: 1.78.0

**Comment by enizor** [comment] 2024-05-16 08:17
Duplicate of #2098, you need to use `cargo install gitui --locked`

**Closed** 2024-05-16 08:48 UTC
Labels: bug, duplicate
