### ISSUE TITLE
unexpected panic

### ISSUE THREAD

**Issue by GertVanKruiningen** [extrawurst/gitui#2431] opened 2024-11-15 09:33 UTC
**Describe the bug**
During normal use, exedently typed F2 in stead of 2 to show earlier commits. Go the message, see below. Not able to use gitui anymore, keep on getting same message when rying to start it. Even uninstalling and installing doesn't help

**To Reproduce**
1. Click on F2
2. See error

**Expected behavior**
Not sure what F2 is, should have typed 2

**Screenshots**
Any { .. }nfo { payload: Any { .. }, location: Location { file: "asyncgit/src/revlog.rs", line: 186, col: 14 }, can_trace:: true, force_no_backtrace: false }
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   7: <unknown>
fish: Job 1, 'gitui' terminated by signal SIGABRT (Abort)
gert@archlinux /m/1/R/ProtonDrive (master) [SIGABRT]> 
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>

**Context (please complete the following information):**
 - OS/Distro + Version: Linux 6.11.7-arch1-1
 - GitUI Version: gitui nightly 2024-09-12 (0f5cf89)

**Comment by extrawurst** [comment] 2024-11-15 09:39
duplicate of https://github.com/extrawurst/gitui/issues/2358 - please use a newer nightly

**Closed by extrawurst** 2024-11-15 09:39 UTC
Labels: bug
