### ISSUE TITLE
feature request: Filter commits from log by string or path

### ISSUE THREAD

**Issue by Kamilcuk** [extrawurst/gitui#2122] opened 2024-03-10 20:59 UTC
**Is your feature request related to a problem? Please describe.**
Gitk has this feature to filter commits based on the filename they include:

![obraz](https://github.com/extrawurst/gitui/assets/15679217/4d620000-a94e-4c7a-a015-7b742b33b1ce)

**Describe the solution you'd like**
In the "Log [2]" view and then typing `/` followed by a search item and pressing enter, it would make all commits with that search item in bold font.

Similarly, typing `P` followed by a glob path item and pressing enter, would display all commits that touch this path in bold.

**Describe alternatives you've considered**
Right now I scroll the commits until I find the file with my eyes or I can do `git log`.

**Additional context**
Gitui is absolutely amazing and I use it daily, it is great and amazing work.

**Comment by extrawurst** [comment] 2024-03-11 07:18
Duplicate of https://github.com/extrawurst/gitui/pull/1800 released in 0.24

**Closed** 2024-03-11 07:23 UTC
Labels: feature-request
