### ISSUE TITLE
commit messages in the log page are sometimes missing

### ISSUE THREAD

**Issue by LangLangBart** [extrawurst/gitui#1473] opened 2022-12-13 12:07 UTC
**Describe the bug**
Sometimes the commit messages are missing, see video below

**To Reproduce**
the steps to reproduce the error could not be clearly determined.
On some repos it functions correctly (showing the commit messages), on other repos it does not. The reason is not clear.
- use the `Log[2]` overview page notice the missing "commit messages"
- when pressing `2` the messages show up correctly

**Expected behavior**
The commit message should always show up.

**Screenshots**
The video first checks the commit messages on the [meiji163/gh-notify](https://github.com/meiji163/gh-notify) repo and then on [extrawurst/gitui](https://github.com/extrawurst/gitui) repo.

https://user-images.githubusercontent.com/92653266/207307694-16a01ea6-7a0b-4960-9921-931c5ca985e7.mp4

**Context (please complete the following information):**
 - OS/Distro + Version: `macOS 10.15` (reproducible with default `Terminal` and `iTerm2`)
 - GitUI Version: `0.22.1`
 - Rust version: `stable 1.65.0 (bottled)` (installed via Homebrew)

**Additional context**
I tried to bisect the issue, but I ended up with the commit 9534e4c2f99111c928dcd2e91ca9fe49364a7ed5, that introduced the feature to save the last page the user viewed.

![bisect](https://user-images.githubusercontent.com/92653266/207313288-9d002253-49c8-47dd-be76-a0c2f0ba57ac.png)

The problem may have been there for a while, but I never noticed it because I always had to press the `2` key to see the log page.

PS: Great tool you have made.

**Comment by kting28** [comment] 2023-02-26 07:17
@extrawurst are you working on this? I took a brief look as I have a repo that constantly hit this bug. It appears if the tab restored at start up is revlog, the `self.git_log.fetch` returns `NoChange` hence not fetching anything:

```
	pub fn update(&mut self) -> Result<()> {
		if self.is_visible() {
			let log_changed =
				self.git_log.fetch()? == FetchStatus::Started;
```
I change log_changed to `true` all the time the issue is not reproduced.  I'm still trying to understand why `head_changed` returns false in this case. Just wants to give you a heads up. If you have any hints let me know. I'd like to take a crack at resolving this.

**Comment by kting28** [comment] 2023-02-26 18:26
@extrawurst  nevermind, after more debugging I think it's unrelated to fetch / needs data. I think the issue only happens with repos with small number of commits. adding some logs to see what's going on.

**Comment by extrawurst** [comment] 2023-03-01 12:21
see #1566

**Closed** 2023-03-01 13:22 UTC
Labels: bug
