### ISSUE TITLE
Program exits unexpectedly 

### ISSUE THREAD

**Issue by iArmanKarimi** [extrawurst/gitui#1756] opened 2023-07-12 00:22 UTC
**Describe the bug**
Deleting a tag from the "Tags" (the panel that shows a list of tags) causes the program to exit.

**To Reproduce**
1. Go to Logs
2. click "t"
3. delete a tag
4. see gitui exit

**Context (please complete the following information):**
 - Windows 11
 - latest version
 - Rust version: I've installed the msi version

**Additional context**

**Comment by extrawurst** [comment] 2023-07-12 11:29
works for me. can you provide the log please

**Comment by iArmanKarimi** [comment] 2023-07-26 15:29
I tried deleting a tag from a local repo that wasn't connected to remote, but it's ok otherwise.
The error message for the local repo which appears after the program exits:
"Error: git: inconclusive remotes"

**Comment by extrawurst** [comment] 2023-08-22 13:34
then its a duplicate of #1093

**Closed by extrawurst** 2023-08-22 13:34 UTC
Labels: bug
