### ISSUE TITLE
Custom Pager Integration (delta, diff-so-fancy, etc)

### ISSUE THREAD

**Issue by JacobTravers** [extrawurst/gitui#650] opened 2021-04-19 18:27 UTC
I think it would be really awesome if we could add an integration for custom pagers like [delta](https://github.com/dandavison/delta) or [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) in the same way [lazygit does](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md) with a config option.

**Comment by bhaak** [comment] 2021-04-29 06:56
If for technical or whatever reasons you prefer an integrated Rust solution, https://github.com/mookid/diffr has a library component.

**Comment by extrawurst** [comment] 2021-04-29 19:59
duplicate of https://github.com/extrawurst/gitui/issues/358

**Closed by extrawurst** 2021-04-29 19:59 UTC
