### ISSUE TITLE
word diff

### ISSUE THREAD

**Issue by asmwarrior** [extrawurst/gitui#584] opened 2021-03-12 03:59 UTC
Can we show the word level diff, if we just add/modify one word in a line.

See this issue  [Word diff · Issue #623 · git-cola/git-cola](https://github.com/git-cola/git-cola/issues/623)

**Comment by spareslant** [comment] 2021-03-24 21:23
+1 for this feature

**Comment by extrawurst** [comment] 2021-04-29 20:00
duplicate of https://github.com/extrawurst/gitui/issues/358

**Closed by extrawurst** 2021-04-29 20:00 UTC
