### ISSUE TITLE
Can't get Arrow keys to work in Konsole on Kubuntu

### ISSUE THREAD

**Issue by Dr-Kristau** [extrawurst/gitui#1027] opened 2021-12-02 21:42 UTC
**Describe the bug**
I can use the arrow keys in Konsole to see my command history, for example, but I can't get the arrow keys to work in gitui.

**Context (please complete the following information):**
- Kubuntu 21.10
- gitui v0.18.0
- rustc 1.56.1

**Additional context**
Arrow keys work fine in gnome-terminal on Ubuntu 20.04.3, not sure why they're not working here.

**Comment by extrawurst** [comment] 2021-12-03 07:21
Can you check if arrow keys work in other apps like tig in the same terminal?

**Comment by Dr-Kristau** [comment] 2021-12-03 08:50
Unfortunately tig doesn't seem to build for me at the moment:
![Screenshot_20211203_094235](https://user-images.githubusercontent.com/32355001/144573356-93605c26-77cd-4adb-8102-f7c39b807dbb.png)

However, the arrow keys do work on the 'sort by' menu of htop:
![Screenshot_20211203_094301](https://user-images.githubusercontent.com/32355001/144573409-5b30eaeb-8665-4770-a575-5bad74cd1165.png)

**Comment by extrawurst** [comment] 2021-12-03 20:55
Ok weird

**Comment by egrieco** [comment] 2022-01-09 01:41
Seeing the same issue on macOS in iTerm2:

ProductName: macOS
ProductVersion: 11.6
BuildVersion: 20G165

iTerm2: Build 3.5.0beta3

zsh: 5.8 (x86_64-apple-darwin20.0)

**Comment by extrawurst** [comment] 2022-01-09 14:43
@egrieco maybe a iterm2 *beta* issue? works fine for me on `3.4.14`

**Comment by callahad** [comment] 2022-01-10 01:09
In case the root cause is the same, I'm also unable to get arrow keys to work on macOS, but using the default Terminal.app. On macOS 12.1, using GitUI 0.19.0 from nixpkgs.

**Comment by extrawurst** [comment] 2022-01-10 09:06
@callahad same for the regular Mac terminal app: **works on my end**. can it be a config in your terminal eating those commands? or did you remap something?

**Comment by callahad** [comment] 2022-01-10 09:57
Fascinating! I don't have any weird customizations to my terminal (heck, I'm even using the built-in Terminal.app; not iTerm2 or Kitty or anything).

...oh no. Now it's working. I haven't changed a thing. This is going to be one of _those_ bugs.

Last night:
- Installed gitui, noticed arrow keys didn't work but all other keys did (numbers to switch tabs, `o` to open options, `esc` to close it, etc.)
- Added the example vim-style `key_bindings.ron`
- Verified that hjkl worked to navigate gitui

This morning:
- Installed iTerm2, hjkl worked as expected
- Quit gitui and removed the `key_bindings.ron` file
- Arrow keys worked in iTerm2
- ...and then also arrow keys worked in Terminal.app

This is in the same exact Terminal.app session from last night; I never closed the window or exited my shell. And yet, now it works.

**Comment by extrawurst** [comment] 2022-01-10 09:58
Maybe a rogue key-logger 🤣

**Comment by extrawurst** [comment] 2022-01-10 21:07
@Dr-Kristau I can't find anything we can do about it and plenty of people have managed to use arrow keys in gitui without issues on all three major platforms. unless we get new insight I am inclined to mark this as closed

**Comment by Dr-Kristau** [comment] 2022-01-11 08:49
I guess if you can't reproduce it and I can't fix it then you might as well!

**Comment by egrieco** [comment] 2022-01-17 02:06
> @egrieco maybe a iterm2 _beta_ issue? works fine for me on `3.4.14`

@extrawurst Might have been memory corruption. The issue seems to be resolved for me after a restart.

**Closed** 2022-10-01 01:56 UTC
Labels: bug, help wanted, dormant, linux

**Comment by l1n3n01z** [comment] 2023-02-02 13:36
Same issue on WSL2.
wsl-mintty and tmux. fish on Ubuntu 20.04.
gitui 0.19.0.

All keys work except moving with arrow keys. Arrow keys work in fish and less and other programs I could think of.

The issue is intermittent. On entry to the program the arrow keys are not working. The issue resolves in a new tmux session or new terminal window. Happens every other day or so.

I have never seen it resolve by itself in the same fish session. Does not resolve by changing to a different git folder or changing folders within the repo or using the git cli or anything.

I think I saw it happen when running bash, but couldn't swear.
I have never had it happen in Windows cmd in Windows terminal, but then again I usually don't have long lived sessions in windows, so less chance of it happening?

**Comment by l1n3n01z** [comment] 2023-04-19 13:54
Was fixed in v0.20.0
See https://github.com/extrawurst/gitui/issues/1533#issuecomment-1514778029
