### ISSUE TITLE
Log don't show at the start 

### ISSUE THREAD

**Issue by Fbrisset** [extrawurst/gitui#1496] opened 2023-01-06 16:46 UTC
**Describe the bug**
When I open gitui on the logs tab. The logs are not displayed, then when I press button 2. They reappear.

**To Reproduce**
1. Open gitui
2. switch to log tab
3. close gitui
4. open gitui and tada

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/95175167/211058008-b3a848e2-8cf3-4c92-839a-c7047e4e8b66.png)

After
![image](https://user-images.githubusercontent.com/95175167/211057470-de8d90b6-c50b-4347-9951-155e7dc7b61f.png)

**Context (please complete the following information):**
 - Debian 11, kernel 5.10.0-20-amd64
 - GitUI Version: 0.22.1
 - Rust version: 1.65.0

**Comment by extrawurst** [comment] 2023-01-29 10:20
duplicate of https://github.com/extrawurst/gitui/issues/1473

**Closed by extrawurst** 2023-01-29 10:20 UTC
Labels: bug
