### ISSUE TITLE
gitui triggers terminal activity all the time, even when it's inactive

### ISSUE THREAD

**Issue by anahata0108** [extrawurst/gitui#764] opened 2021-06-03 16:16 UTC
**Describe the bug**
When I have gitui running in an iTerm tab, gitui triggers activity in the tab when I switch to another tab, despite the program being idle. I imagine it triggers for other terminal emulators, but I'm not in a position to easily test this.

**To Reproduce**
1. Open an iTerm2 window with some tabs configured to show terminal activity
2. Open gitui in a tab
3. Switch to another tab
4. Observe activity in gitui's tab despite the program being idle

**Expected behavior**
I would expect an idle program to not trigger activity in my terminal emulator.

**Context (please complete the following information):**
 - macOS 11.4
 - GitUI Version 0.16
 - Rust version: 1.52.1

**Additional context**
This happens in very large repos (e.g. a full clone of rust-lang/rust) and medium size repos (a work project), but not some nascent personal projects with just a few commits.

**Comment by extrawurst** [comment] 2021-06-03 16:26
duplicate of #523

**Comment by anahata0108** [comment] 2021-06-03 16:28
I’m not sure this is the case; an application can run without triggering activity in the terminal. Things like vim run in my terminal all day and don’t trigger activity. Am I missing something?

**Comment by extrawurst** [comment] 2021-06-03 16:30
> I’m not sure this is the case

what does that mean, do you think you observe a different issue than #523 ?

**Comment by anahata0108** [comment] 2021-06-03 16:33
Yes. My terminal is configured to flag activity on output, not based on whether the application in the terminal is on the CPU. If I delay output to the terminal (e.g. something like `sleep 5; echo hi`), and switch to another tab, in 5 seconds my terminal will flag for activity just like gitui does when it's inactive.

**Comment by extrawurst** [comment] 2021-06-03 16:41
> configured to flag activity

how does this work? will this be triggered if anything is updated on the terminal text buffer?

**Comment by extrawurst** [comment] 2021-06-03 16:42
are you referring to this iterm2 graphic?

<img width="87" alt="Screenshot 2021-06-03 at 18 42 26" src="https://user-images.githubusercontent.com/776816/120681230-74979c00-c49b-11eb-9b7c-2f31aeb3378f.png">

**Comment by anahata0108** [comment] 2021-06-05 22:43
Hello!

It's the new-output indicator, not the activity indicator, my apologies. It's right below the activity indicator in the preferences and looks like this:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/44044/120907241-f0c1e900-c62d-11eb-9ef6-961ccf49189b.png">

**Comment by extrawurst** [comment] 2021-06-06 00:11
@anahata0108 I found the reason why that indicator lighted up all the time, this is fixed and now aligned exactly with the 2 second interval of us polling for changes on the file system. this means now it is a dup of #1 and will be better once we have that implemented and do not need to poll anymore.

**Closed by extrawurst** 2021-06-06 00:11 UTC
Labels: question
