### ISSUE TITLE
Cache commit message in case commit is aborted

### ISSUE THREAD

**Issue by stevejalim** [extrawurst/gitui#1083] opened 2022-01-19 14:39 UTC
**Is your feature request related to a problem? Please describe.**
When using pre-commit hooks, it's possible that a well-intentioned commit will be rejected by those hooks. If one has just written a long commit message (using the external editor or just the smaller in-GUI dialog) and the commit is aborted, the commit note is lost.

**Describe the solution you'd like**
 It would be great if the commit message was cached/stashed somewhere to avoid rework in the case of commit failure.

**Additional context**
I'm personally using the `pre-commit` framework, but I think this stands for anyone using pre-commit hooks

**Comment by extrawurst** [comment] 2022-01-19 14:52
Can you link me that pre commit framework you were referring to? I am asking cause I recently looked into husky for #1019

**Comment by stevejalim** [comment] 2022-01-19 15:04
Sure thing - it's https://pre-commit.com/ - and gitui does run the hooks, happily 😄 

There's also [Therapist](https://github.com/rehandalal/therapist) which does a similar job

**Comment by extrawurst** [comment] 2022-01-19 15:12
Also see #937

**Comment by extrawurst** [comment] 2022-09-18 14:26
I am not sure what the problem is. If I create a pre-commit hook that always rejects it does not clear the commit message?

<img width="1194" alt="Screenshot 2022-09-18 at 16 25 20" src="https://user-images.githubusercontent.com/776816/190912013-489db324-217d-42a3-be28-ba1360940f7a.png">

**Comment by extrawurst** [comment] 2022-09-18 14:28
this was actually implemented in 6249491 and released in `0.20`

**Closed by extrawurst** 2022-09-18 14:28 UTC
Labels: enhancement, good first issue
