### ISSUE TITLE
Panic when trying to see branches

### ISSUE THREAD

**Issue by TheRoniOne** [extrawurst/gitui#1691] opened 2023-05-16 17:23 UTC
**Describe the bug**
Panic happening when trying to see branches.

**To Reproduce**
In a terminal:
1. gitui
2. Press "b" key while in "Status" tab
3. Panic happens and crashes gitui

**Expected behavior**
It should show the existing branches instead of ending in a panic.

**Screenshots**
```
17:11:00 [TRACE] (4) asyncgit::status: [/home/roni/.cargo/registry/src/github.com-1ecc6299db9ec823/asyncgit-0.22.1/src/status.rs:160] status fetched: 3211755944333863709 (type: Stage)
17:11:00 [TRACE] (1) gitui::app: [/home/roni/.cargo/registry/src/github.com-1ecc6299db9ec823/gitui-0.22.1/src/app.rs:496] update_async: Git(Status)
17:11:00 [TRACE] (3) asyncgit::status: [/home/roni/.cargo/registry/src/github.com-1ecc6299db9ec823/asyncgit-0.22.1/src/status.rs:160] status fetched: 14251936748505898918 (type: WorkingDir)
17:11:00 [TRACE] (1) gitui::app: [/home/roni/.cargo/registry/src/github.com-1ecc6299db9ec823/gitui-0.22.1/src/app.rs:496] update_async: Git(Status)
17:11:03 [TRACE] (1) gitui::app: [/home/roni/.cargo/registry/src/github.com-1ecc6299db9ec823/gitui-0.22.1/src/app.rs:382] event: Input(Key(KeyEvent { code: Char('b'), modifiers: NONE, kind: Press, state: NONE }))
17:11:03 [ERROR] panic: PanicInfo { payload: Any { .. }, message: Some(assertion failed: min <= max), location: Location { file: "/rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/cmp.rs", line: 869, col: 9 }, can_unwind: true }
trace:
   0: gitui::set_panic_handlers::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   6: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   7: core::cmp::Ord::clamp
   8: gitui::ui::rect_inside
   9: gitui::app::App::draw_popups
  10: gitui::app::App::draw
  11: gitui::run_app
  12: gitui::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: main
  15: __libc_start_main
  16: _start

```

**Context (please complete the following information):**
 - OS/Distro + Version: Ubuntu 20.04.6 LTS (in WSL2)
 - GitUI Version: 0.22.1
 - Rust version: 1.65

**Comment by pm100** [comment] 2023-05-18 15:51
i suspect that this is fixed by this https://github.com/extrawurst/gitui/issues/1470, which will be in the next release 

it is caused by the terminal window being too narrow

**Comment by extrawurst** [comment] 2023-12-15 07:53
This was fixed in the last release

**Closed by extrawurst** 2023-12-15 07:53 UTC
Labels: bug, dormant
