### ISSUE TITLE
GitUI was close due to an unexpected panic

### ISSUE THREAD

**Issue by RubberJones** [extrawurst/gitui#2137] opened 2024-03-19 16:29 UTC
**Description**
If I use 'Blame' on my file, the application crashes. The file is in JSON format.

**Reproduce**
If I open the commit with the JSON file with the right arrow and then press 'Blame', the programme crashes with this message.

**Output**
PanicInfo { payload: Any { .. }, message: Some(index out of bounds: the len is 60 but the index is 60), location: Location { file: "src/popups/blame_file.rs", line: 622, col: 38 }, can_unwind: true, force_no_backtrace: false }
trace:
   0: gitui::set_panic_handlers::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: gitui::app::App::draw_popups
   8: gitui::app::App::draw
   9: gitui::run_app
  10: gitui::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_call_main
  14: __libc_start_main_impl
  15: _start

**Context**
- OS: Fedora 39, 6.7.9-200.fc39.x86_64
- git version: 2.44.0
- Rust version: 1.76.0 (c84b36747 2024-01-18)

**Comment by extrawurst** [comment] 2024-03-20 00:37
duplicate of #2130

**Closed by extrawurst** 2024-03-20 00:37 UTC
Labels: bug
