### ISSUE TITLE
Crashes with overlays in small-sized window

### ISSUE THREAD

**Issue by AnonymouX47** [extrawurst/gitui#1585] opened 2023-03-04 06:36 UTC
**Describe the bug**
Git UI crashes (with error code 101) when an overlay is open and the terminal size is small (in my case, width < 60 columns and/or height < 20 lines). Overlays I tried include the **Branches** and **Submodules** views but there may be others.

**To Reproduce**
1. Go to the **Status** tab.
3. Resize the terminal window till the width is less than 60 columns or height less than 20 lines.
2. Hit `b` (or whatever key) for the **Branches** view.
4. Crashes with error code 101.

Also occurs if the terminal window is resized after the overlay has been opened.

**Expected behavior**
The overlay should automatically readjust to fit within the terminal window, possibly by clipping it's content per line.

**Context (please complete the following information):**
#### Software version

gitui 0.22.1

#### Operating system

Linux 5.15.94-1-MANJARO

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=vim
GIT_EDITOR=<not set>
VISUAL=<not set>
```

**Additional context**
Relevant logs (produced with `gitui -l`):
```
...
06:29:49 [TRACE] (1) gitui::app: [src/app.rs:382] event: Input(Key(KeyEvent { code: Char('b'), modifiers: NONE, kind: Press, state: NONE }))
06:29:51 [TRACE] (1) gitui::app: [src/app.rs:382] event: Input(Resize(60, 30))
06:29:52 [TRACE] (1) gitui::app: [src/app.rs:382] event: Input(Resize(59, 30))
06:29:52 [ERROR] panic: PanicInfo { payload: Any { .. }, message: Some(assertion failed: min <= max), location: Location { file: "/rustc/1.65.0/library/core/src/cmp.rs", line: 869, col: 9 }, can_unwind: true }
trace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_main
  17: <unknown>
EOF
```

**Comment by extrawurst** [comment] 2023-03-04 16:21
duplicate of https://github.com/extrawurst/gitui/issues/1470

**Closed by extrawurst** 2023-03-04 16:21 UTC
Labels: bug
