### ISSUE TITLE
Support git commit body

### ISSUE THREAD

**Issue by pacghost** [extrawurst/gitui#1347] opened 2022-09-20 07:46 UTC
**Is your feature request related to a problem? Please describe.**
When doing a commit in gitui, I often need to use the external editor because gitui does not allow for git commit body text.

**Describe the solution you'd like**
To be able to make a new line in the git commit window to add a git commit body and not only the subject as it is now.

**Describe alternatives you've considered**
Right now I am forced to use the external editor, which kind of defeat the purpose of using gitui for such a simple thing as a commit.

**Comment by extrawurst** [comment] 2022-09-20 08:10
duplicate of #1171

**Closed by extrawurst** 2022-09-20 08:10 UTC
Labels: feature-request
